[workspace]
members = ["packages/*"]
resolver = "2"

[workspace.dependencies]
vexide = "0.8.0"
evian = { path = "../evian/packages/evian" }
aubie2 = { path = "packages/aubie2" }
log = "0.4.28"

[profile.release]
opt-level = "z"
lto = "fat"