[package]
name = "nemo"
version = "0.1.0"
edition = "2024"

[package.metadata.v5]
upload-strategy = "differential"
slot = 1
icon = "cool-x"

[dependencies]
aubie2 = { workspace = true }
vexide = { workspace = true, features = ["full", "default-sdk"] }
evian = { workspace = true }
log = { workspace = true }
futures = { version = "0.3.31", default-features = false, features = ["async-await"] }
