[package]
name = "aubie2"
version = "0.1.0"
edition = "2024"

[dependencies]
vexide = { workspace = true }
evian = { workspace = true }
log = { workspace = true }
bitflags = "2.10.0"
vex-sdk = "0.28.0"